version: '3.8'
services:
  application:
    build:
      context: .
      args:
        EPHEMERAL_DB: true
    environment:
      SQLALCHEMY_URL: "postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@database:5432/${DB_NAME}"
      BUGCROWD_API_KEY: "${BUGCROWD_API_KEY}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      # Other environment variables here...
    depends_on:
      - database
    restart: unless-stopped # Automatically restart the container if it crashes

  database:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - db_data:/var/lib/postgresql/data # Persist database data (TIP: to remove, run --> docker-compose down -v)
    restart: unless-stopped # Automatically restart the container if it crashes

volumes:
  db_data: # Volume to persist database data
